In [1]:
# What is the problem here in the dataset
# What we understand in this project

In [ ]:
# API
# Application Programming Interface
# API Key is Security code.

In [ ]:
# install kaggle
#!pip install kaggle

In [ ]:
# It is kind of ETL Project.
# We extracted data from kaggle api, we did data cleaning, transformation in python.
# Then loaded the data into sql server.

In [1]:
import os
os.environ["KAGGLE_API_TOKEN"] = "KGAT_82c34aae790b20818debb4d29d871fc6"
os.environ["KAGGLE_USERNAME"] = "priyachoudhary09"
os.environ["KAGGLE_KEY"]      = "KGAT_82c34aae790b20818debb4d29d871fc6"


# now import
import kaggle

In [2]:
!kaggle -v

Kaggle API 1.8.2

In [3]:
#!kaggle competitions list

In [4]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [5]:
import zipfile

In [6]:
zip_ref = zipfile.ZipFile('orders.csv.zip', 'r')  # 'r' for read mode
zip_ref.extractall()  # Extracts all files in the current directory
zip_ref.close()

In [1]:
# read data from the file and handle null values
import pandas as pd

df = pd.read_csv('orders.csv')

In [2]:
print(df)

      Order Id  Order Date       Ship Mode    Segment        Country  \
0            1  2023-03-01    Second Class   Consumer  United States
1            2  2023-08-15    Second Class   Consumer  United States
2            3  2023-01-10    Second Class  Corporate  United States
3            4  2022-06-18  Standard Class   Consumer  United States
4            5  2022-07-13  Standard Class   Consumer  United States
...        ...         ...             ...        ...            ...
9989      9990  2023-02-18    Second Class   Consumer  United States
9990      9991  2023-03-17  Standard Class   Consumer  United States
9991      9992  2022-08-07  Standard Class   Consumer  United States
9992      9993  2022-11-19  Standard Class   Consumer  United States
9993      9994  2022-07-17    Second Class   Consumer  United States

                 City       State  Postal Code Region         Category  \
0           Henderson    Kentucky        42420  South        Furniture
1           Henderson    Kentucky        42420  South        Furniture
2         Los Angeles  California        90036   West  Office Supplies
3     Fort Lauderdale     Florida        33311  South        Furniture
4     Fort Lauderdale     Florida        33311  South  Office Supplies
...               ...         ...          ...    ...              ...
9989            Miami     Florida        33180  South        Furniture
9990       Costa Mesa  California        92627   West        Furniture
9991       Costa Mesa  California        92627   West       Technology
9992       Costa Mesa  California        92627   West  Office Supplies
9993      Westminster  California        92683   West  Office Supplies

     Sub Category       Product Id  cost price  List Price  Quantity  \
0       Bookcases  FUR-BO-10001798         240         260         2
1          Chairs  FUR-CH-10000454         600         730         3
2          Labels  OFF-LA-10000240          10          10         2
3          Tables  FUR-TA-10000577         780         960         5
4         Storage  OFF-ST-10000760          20          20         2
...           ...              ...         ...         ...       ...
9989  Furnishings  FUR-FU-10001889          30          30         3
9990  Furnishings  FUR-FU-10000747          70          90         2
9991       Phones  TEC-PH-10003645         220         260         2
9992        Paper  OFF-PA-10004041          30          30         4
9993   Appliances  OFF-AP-10002684         210         240         2

      Discount Percent
0                    2
1                    3
2                    5
3                    2
4                    5
...                ...
9989                 4
9990                 4
9991                 2
9992                 3
9993                 3

[9994 rows x 16 columns]

In [3]:
# Shows the first 20 rows of the Data
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,Not Available,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,unknown,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [4]:
# Show all unique values in the 'Ship Mode' column
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [5]:
# nan is treated as null.

In [6]:
# Read csv file and treat 'Not Available' and 'unknown' as missing values (NaN)
df = pd.read_csv('orders.csv',na_values=['Not Available', 'unknown'])

In [7]:
# Now this value , 'Not Available', 'unknown' is treated as null.

In [8]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [9]:
# rename column names , make them lower case and replace space with underscore.
df.rename(columns = {'Order Id' :'order_id', 'City': 'city'})

,order_id,Order Date,Ship Mode,Segment,Country,city,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [10]:
 # Shows all column names in the Data
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   object
 2   Ship Mode         9988 non-null   object
 3   Segment           9994 non-null   object
 4   Country           9994 non-null   object
 5   City              9994 non-null   object
 6   State             9994 non-null   object
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   object
 9   Category          9994 non-null   object
 10  Sub Category      9994 non-null   object
 11  Product Id        9994 non-null   object
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), object(10)
memory usage: 1.2+ MB

In [12]:
df.shape

(9994, 16)

In [16]:
# I analyzed a sales dataset with 9,994 records and 16 columns, including order details, customer location, product info, pricing, quantity, and discounts.

In [17]:
# Convert all column names to lowercase
df.columns = df.columns.str.lower()

In [18]:
df.columns

Index(['order id', 'order date', 'ship mode', 'segment', 'country', 'city',
       'state', 'postal code', 'region', 'category', 'sub category',
       'product id', 'cost price', 'list price', 'quantity',
       'discount percent'],
      dtype='object')

In [19]:
# Replace spaces in column names with underscores.
df.columns = df.columns.str.replace(' ','_')

In [20]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [21]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [22]:
# derive new columns discount, sale price and profit.
# 1% = 1 / 100 = 0.01

# Calculate the discount amount (list price * discount percent ÷ 100)
df['discount'] = df['list_price']*df['discount_percent']/100

In [23]:
print(df['discount'])

0        5.2
1       21.9
2        0.5
3       19.2
4        1.0
        ...
9989     1.2
9990     3.6
9991     5.2
9992     0.9
9993     7.2
Name: discount, Length: 9994, dtype: float64

In [24]:
print(df)

      order_id  order_date       ship_mode    segment        country  \
0            1  2023-03-01    Second Class   Consumer  United States
1            2  2023-08-15    Second Class   Consumer  United States
2            3  2023-01-10    Second Class  Corporate  United States
3            4  2022-06-18  Standard Class   Consumer  United States
4            5  2022-07-13  Standard Class   Consumer  United States
...        ...         ...             ...        ...            ...
9989      9990  2023-02-18    Second Class   Consumer  United States
9990      9991  2023-03-17  Standard Class   Consumer  United States
9991      9992  2022-08-07  Standard Class   Consumer  United States
9992      9993  2022-11-19  Standard Class   Consumer  United States
9993      9994  2022-07-17    Second Class   Consumer  United States

                 city       state  postal_code region         category  \
0           Henderson    Kentucky        42420  South        Furniture
1           Henderson    Kentucky        42420  South        Furniture
2         Los Angeles  California        90036   West  Office Supplies
3     Fort Lauderdale     Florida        33311  South        Furniture
4     Fort Lauderdale     Florida        33311  South  Office Supplies
...               ...         ...          ...    ...              ...
9989            Miami     Florida        33180  South        Furniture
9990       Costa Mesa  California        92627   West        Furniture
9991       Costa Mesa  California        92627   West       Technology
9992       Costa Mesa  California        92627   West  Office Supplies
9993      Westminster  California        92683   West  Office Supplies

     sub_category       product_id  cost_price  list_price  quantity  \
0       Bookcases  FUR-BO-10001798         240         260         2
1          Chairs  FUR-CH-10000454         600         730         3
2          Labels  OFF-LA-10000240          10          10         2
3          Tables  FUR-TA-10000577         780         960         5
4         Storage  OFF-ST-10000760          20          20         2
...           ...              ...         ...         ...       ...
9989  Furnishings  FUR-FU-10001889          30          30         3
9990  Furnishings  FUR-FU-10000747          70          90         2
9991       Phones  TEC-PH-10003645         220         260         2
9992        Paper  OFF-PA-10004041          30          30         4
9993   Appliances  OFF-AP-10002684         210         240         2

      discount_percent  discount
0                    2       5.2
1                    3      21.9
2                    5       0.5
3                    2      19.2
4                    5       1.0
...                ...       ...
9989                 4       1.2
9990                 4       3.6
9991                 2       5.2
9992                 3       0.9
9993                 3       7.2

[9994 rows x 17 columns]

In [25]:
# Sale price = List price minus Discount
df['sale price'] = df['list_price']-df['discount']

In [26]:
print(df)

      order_id  order_date       ship_mode    segment        country  \
0            1  2023-03-01    Second Class   Consumer  United States
1            2  2023-08-15    Second Class   Consumer  United States
2            3  2023-01-10    Second Class  Corporate  United States
3            4  2022-06-18  Standard Class   Consumer  United States
4            5  2022-07-13  Standard Class   Consumer  United States
...        ...         ...             ...        ...            ...
9989      9990  2023-02-18    Second Class   Consumer  United States
9990      9991  2023-03-17  Standard Class   Consumer  United States
9991      9992  2022-08-07  Standard Class   Consumer  United States
9992      9993  2022-11-19  Standard Class   Consumer  United States
9993      9994  2022-07-17    Second Class   Consumer  United States

                 city       state  postal_code region         category  \
0           Henderson    Kentucky        42420  South        Furniture
1           Henderson    Kentucky        42420  South        Furniture
2         Los Angeles  California        90036   West  Office Supplies
3     Fort Lauderdale     Florida        33311  South        Furniture
4     Fort Lauderdale     Florida        33311  South  Office Supplies
...               ...         ...          ...    ...              ...
9989            Miami     Florida        33180  South        Furniture
9990       Costa Mesa  California        92627   West        Furniture
9991       Costa Mesa  California        92627   West       Technology
9992       Costa Mesa  California        92627   West  Office Supplies
9993      Westminster  California        92683   West  Office Supplies

     sub_category       product_id  cost_price  list_price  quantity  \
0       Bookcases  FUR-BO-10001798         240         260         2
1          Chairs  FUR-CH-10000454         600         730         3
2          Labels  OFF-LA-10000240          10          10         2
3          Tables  FUR-TA-10000577         780         960         5
4         Storage  OFF-ST-10000760          20          20         2
...           ...              ...         ...         ...       ...
9989  Furnishings  FUR-FU-10001889          30          30         3
9990  Furnishings  FUR-FU-10000747          70          90         2
9991       Phones  TEC-PH-10003645         220         260         2
9992        Paper  OFF-PA-10004041          30          30         4
9993   Appliances  OFF-AP-10002684         210         240         2

      discount_percent  discount  sale price
0                    2       5.2       254.8
1                    3      21.9       708.1
2                    5       0.5         9.5
3                    2      19.2       940.8
4                    5       1.0        19.0
...                ...       ...         ...
9989                 4       1.2        28.8
9990                 4       3.6        86.4
9991                 2       5.2       254.8
9992                 3       0.9        29.1
9993                 3       7.2       232.8

[9994 rows x 18 columns]

In [34]:
# Calculate profit for each item
df['profit'] = df['sale price'] - df['cost_price']

In [35]:
print(df)

      order_id  order_date       ship_mode    segment        country  \
0            1  2023-03-01    Second Class   Consumer  United States
1            2  2023-08-15    Second Class   Consumer  United States
2            3  2023-01-10    Second Class  Corporate  United States
3            4  2022-06-18  Standard Class   Consumer  United States
4            5  2022-07-13  Standard Class   Consumer  United States
...        ...         ...             ...        ...            ...
9989      9990  2023-02-18    Second Class   Consumer  United States
9990      9991  2023-03-17  Standard Class   Consumer  United States
9991      9992  2022-08-07  Standard Class   Consumer  United States
9992      9993  2022-11-19  Standard Class   Consumer  United States
9993      9994  2022-07-17    Second Class   Consumer  United States

                 city       state  postal_code region         category  \
0           Henderson    Kentucky        42420  South        Furniture
1           Henderson    Kentucky        42420  South        Furniture
2         Los Angeles  California        90036   West  Office Supplies
3     Fort Lauderdale     Florida        33311  South        Furniture
4     Fort Lauderdale     Florida        33311  South  Office Supplies
...               ...         ...          ...    ...              ...
9989            Miami     Florida        33180  South        Furniture
9990       Costa Mesa  California        92627   West        Furniture
9991       Costa Mesa  California        92627   West       Technology
9992       Costa Mesa  California        92627   West  Office Supplies
9993      Westminster  California        92683   West  Office Supplies

     sub_category       product_id  cost_price  list_price  quantity  \
0       Bookcases  FUR-BO-10001798         240         260         2
1          Chairs  FUR-CH-10000454         600         730         3
2          Labels  OFF-LA-10000240          10          10         2
3          Tables  FUR-TA-10000577         780         960         5
4         Storage  OFF-ST-10000760          20          20         2
...           ...              ...         ...         ...       ...
9989  Furnishings  FUR-FU-10001889          30          30         3
9990  Furnishings  FUR-FU-10000747          70          90         2
9991       Phones  TEC-PH-10003645         220         260         2
9992        Paper  OFF-PA-10004041          30          30         4
9993   Appliances  OFF-AP-10002684         210         240         2

      discount_percent  discount  sale price  profit
0                    2       5.2       254.8    14.8
1                    3      21.9       708.1   108.1
2                    5       0.5         9.5    -0.5
3                    2      19.2       940.8   160.8
4                    5       1.0        19.0    -1.0
...                ...       ...         ...     ...
9989                 4       1.2        28.8    -1.2
9990                 4       3.6        86.4    16.4
9991                 2       5.2       254.8    34.8
9992                 3       0.9        29.1    -0.9
9993                 3       7.2       232.8    22.8

[9994 rows x 19 columns]

In [36]:
# Show the new columns
print(df[['discount', 'sale price', 'profit']])

      discount  sale price  profit
0          5.2       254.8    14.8
1         21.9       708.1   108.1
2          0.5         9.5    -0.5
3         19.2       940.8   160.8
4          1.0        19.0    -1.0
...        ...         ...     ...
9989       1.2        28.8    -1.2
9990       3.6        86.4    16.4
9991       5.2       254.8    34.8
9992       0.9        29.1    -0.9
9993       7.2       232.8    22.8

[9994 rows x 3 columns]

In [33]:
# Show the first 10 rows of the data.
print(df.head(10))

   order_id  order_date       ship_mode    segment        country  \
0         1  2023-03-01    Second Class   Consumer  United States
1         2  2023-08-15    Second Class   Consumer  United States
2         3  2023-01-10    Second Class  Corporate  United States
3         4  2022-06-18  Standard Class   Consumer  United States
4         5  2022-07-13  Standard Class   Consumer  United States
5         6  2022-03-13             NaN   Consumer  United States
6         7  2022-12-28  Standard Class   Consumer  United States
7         8  2022-01-25  Standard Class   Consumer  United States
8         9  2023-03-23             NaN   Consumer  United States
9        10  2023-05-16  Standard Class   Consumer  United States

              city       state  postal_code region         category  \
0        Henderson    Kentucky        42420  South        Furniture
1        Henderson    Kentucky        42420  South        Furniture
2      Los Angeles  California        90036   West  Office Supplies
3  Fort Lauderdale     Florida        33311  South        Furniture
4  Fort Lauderdale     Florida        33311  South  Office Supplies
5      Los Angeles  California        90032   West        Furniture
6      Los Angeles  California        90032   West  Office Supplies
7      Los Angeles  California        90032   West       Technology
8      Los Angeles  California        90032   West  Office Supplies
9      Los Angeles  California        90032   West  Office Supplies

  sub_category       product_id  cost_price  list_price  quantity  \
0    Bookcases  FUR-BO-10001798         240         260         2
1       Chairs  FUR-CH-10000454         600         730         3
2       Labels  OFF-LA-10000240          10          10         2
3       Tables  FUR-TA-10000577         780         960         5
4      Storage  OFF-ST-10000760          20          20         2
5  Furnishings  FUR-FU-10001487          50          50         7
6          Art  OFF-AR-10002833          10          10         4
7       Phones  TEC-PH-10002275         860         910         6
8      Binders  OFF-BI-10003910          20          20         3
9   Appliances  OFF-AP-10002892          90         110         5

   discount_percent  discount  sale price  profit
0                 2       5.2       254.8    14.8
1                 3      21.9       708.1   108.1
2                 5       0.5         9.5    -0.5
3                 2      19.2       940.8   160.8
4                 5       1.0        19.0    -1.0
5                 3       1.5        48.5    -1.5
6                 3       0.3         9.7    -0.3
7                 5      45.5       864.5     4.5
8                 2       0.4        19.6    -0.4
9                 3       3.3       106.7    16.7

In [27]:
# Check datatypes
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale price          float64
dtype: object

In [28]:
# Convert order date from object data type to datetime
df['order_date'] = pd.to_datetime(df['order_date'],format = "%Y-%m-%d")

In [29]:
print(df)

      order_id order_date       ship_mode    segment        country  \
0            1 2023-03-01    Second Class   Consumer  United States
1            2 2023-08-15    Second Class   Consumer  United States
2            3 2023-01-10    Second Class  Corporate  United States
3            4 2022-06-18  Standard Class   Consumer  United States
4            5 2022-07-13  Standard Class   Consumer  United States
...        ...        ...             ...        ...            ...
9989      9990 2023-02-18    Second Class   Consumer  United States
9990      9991 2023-03-17  Standard Class   Consumer  United States
9991      9992 2022-08-07  Standard Class   Consumer  United States
9992      9993 2022-11-19  Standard Class   Consumer  United States
9993      9994 2022-07-17    Second Class   Consumer  United States

                 city       state  postal_code region         category  \
0           Henderson    Kentucky        42420  South        Furniture
1           Henderson    Kentucky        42420  South        Furniture
2         Los Angeles  California        90036   West  Office Supplies
3     Fort Lauderdale     Florida        33311  South        Furniture
4     Fort Lauderdale     Florida        33311  South  Office Supplies
...               ...         ...          ...    ...              ...
9989            Miami     Florida        33180  South        Furniture
9990       Costa Mesa  California        92627   West        Furniture
9991       Costa Mesa  California        92627   West       Technology
9992       Costa Mesa  California        92627   West  Office Supplies
9993      Westminster  California        92683   West  Office Supplies

     sub_category       product_id  cost_price  list_price  quantity  \
0       Bookcases  FUR-BO-10001798         240         260         2
1          Chairs  FUR-CH-10000454         600         730         3
2          Labels  OFF-LA-10000240          10          10         2
3          Tables  FUR-TA-10000577         780         960         5
4         Storage  OFF-ST-10000760          20          20         2
...           ...              ...         ...         ...       ...
9989  Furnishings  FUR-FU-10001889          30          30         3
9990  Furnishings  FUR-FU-10000747          70          90         2
9991       Phones  TEC-PH-10003645         220         260         2
9992        Paper  OFF-PA-10004041          30          30         4
9993   Appliances  OFF-AP-10002684         210         240         2

      discount_percent  discount  sale price
0                    2       5.2       254.8
1                    3      21.9       708.1
2                    5       0.5         9.5
3                    2      19.2       940.8
4                    5       1.0        19.0
...                ...       ...         ...
9989                 4       1.2        28.8
9990                 4       3.6        86.4
9991                 2       5.2       254.8
9992                 3       0.9        29.1
9993                 3       7.2       232.8

[9994 rows x 18 columns]

In [30]:
# Check datatypes
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale price                 float64
dtype: object

In [31]:
# drop cost price,list price and discount percent columns and update the data.
df.drop(columns=['cost_price','list_price','discount_percent'], inplace = True)

In [32]:
print(df)

      order_id order_date       ship_mode    segment        country  \
0            1 2023-03-01    Second Class   Consumer  United States
1            2 2023-08-15    Second Class   Consumer  United States
2            3 2023-01-10    Second Class  Corporate  United States
3            4 2022-06-18  Standard Class   Consumer  United States
4            5 2022-07-13  Standard Class   Consumer  United States
...        ...        ...             ...        ...            ...
9989      9990 2023-02-18    Second Class   Consumer  United States
9990      9991 2023-03-17  Standard Class   Consumer  United States
9991      9992 2022-08-07  Standard Class   Consumer  United States
9992      9993 2022-11-19  Standard Class   Consumer  United States
9993      9994 2022-07-17    Second Class   Consumer  United States

                 city       state  postal_code region         category  \
0           Henderson    Kentucky        42420  South        Furniture
1           Henderson    Kentucky        42420  South        Furniture
2         Los Angeles  California        90036   West  Office Supplies
3     Fort Lauderdale     Florida        33311  South        Furniture
4     Fort Lauderdale     Florida        33311  South  Office Supplies
...               ...         ...          ...    ...              ...
9989            Miami     Florida        33180  South        Furniture
9990       Costa Mesa  California        92627   West        Furniture
9991       Costa Mesa  California        92627   West       Technology
9992       Costa Mesa  California        92627   West  Office Supplies
9993      Westminster  California        92683   West  Office Supplies

     sub_category       product_id  quantity  discount  sale price
0       Bookcases  FUR-BO-10001798         2       5.2       254.8
1          Chairs  FUR-CH-10000454         3      21.9       708.1
2          Labels  OFF-LA-10000240         2       0.5         9.5
3          Tables  FUR-TA-10000577         5      19.2       940.8
4         Storage  OFF-ST-10000760         2       1.0        19.0
...           ...              ...       ...       ...         ...
9989  Furnishings  FUR-FU-10001889         3       1.2        28.8
9990  Furnishings  FUR-FU-10000747         2       3.6        86.4
9991       Phones  TEC-PH-10003645         2       5.2       254.8
9992        Paper  OFF-PA-10004041         4       0.9        29.1
9993   Appliances  OFF-AP-10002684         2       7.2       232.8

[9994 rows x 15 columns]

In [50]:
# Load the data into sql server using replace option.
import mysql.connector
import sqlalchemy
import pandas as pd
import pymysql
import sys

In [51]:
# Import to connect to database and run SQL
# create_engine is for connecting to the database.
# text is for running SQL queries.
from sqlalchemy import create_engine, text

In [52]:
# Connects to the MySQL database sys.
engine = create_engine("mysql+pymysql://root:Mysql@127.0.0.1:3306/sys")
# username - root                       
# password - Mysql
# hostname - 127.0.0.1  -->localhost
# port - 3306
# database - sys

In [53]:
import pandas as pd
from sqlalchemy import create_engine

# Connection string
engine = create_engine(
    "mssql+pyodbc://@LAPTOP-JARF041B/namestesql?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

In [54]:
# Go to sql server
# right click on that select properties
# This is my server name LAPTOP-JARF041B

In [55]:
# Load the data into sql server using append option
df.to_sql('df_orders', con=engine, index = False, if_exists = 'append')

-1

In [56]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'quantity', 'discount', 'sale_price', 'profit'],
      dtype='object')

In [57]:
df.rename(columns={'sale price': 'sale_price'}, inplace=True)

In [58]:
df['profit'] = 0

In [59]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'quantity', 'discount', 'sale_price', 'profit'],
      dtype='object')